fooddiary/config/routes.rb
Rails.application.routes.draw do
  #devise_for :users
  get 'sessions/new'
  get 'welcome/index'

  #resources :users

  resources :diaries do
    resources :comments
  end

  get 'login' => 'sessions#new' 
  post 'login' => 'sessions#create' 
  delete 'logout' => 'sessions#destroy'

  root 'welcome#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

fooddiary/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

fooddiary/app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :diary
  #belongs_to :user
end

fooddiary/app/models/diary.rb
class Diary < ApplicationRecord
    #belongs_to :user

    mount_uploader :image, ImageUploader
    has_many :comments, dependent: :destroy
    validates :foodname, presence: true,
                    length: { minimum: 1 }
end

fooddiary/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
    before_save { self.email = email.downcase } 
    validates :name, presence: true, length: { maximum: 50 } 
    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i 
    validates :email, presence: true, length: { maximum: 255 }, format: { with: VALID_EMAIL_REGEX }, uniqueness: { case_sensitive: false }
    has_secure_password

    has_many :diary 
    has_many :comments



end

fooddiary/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    protect_from_forgery with: :exception 
    include SessionsHelper
end

fooddiary/app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    http_basic_authenticate_with name: "a", password: "a", only: :destroy
    
    def create
        @diary = Diary.find(params[:diary_id])
        @comment = @diary.comments.create(comment_params)
        redirect_to diary_path(@diary)
      end

      def destroy
        @diary = Aiary.find(params[:diary_id])
        @comment = @diary.comments.find(params[:id])
        @comment.destroy
        redirect_to diary_path(@diary)
      end
     
      private
        def comment_params
          params.require(:comment).permit(:calorie, :time, :day ,:bld)
        end
end

fooddiary/app/controllers/diaries_controller.rb
class DiariesController < ApplicationController
    http_basic_authenticate_with name: "a", password: "a", except: [:index, :show]
    def index
        @diaries = Diary.all
    end

      
    def show
        @diary = Diary.find(params[:id])
    end
    
    def new
        @diary = Diary.new #새로운 인스턴스 변수 만들기
    end

    def edit
        @diary = Diary.find(params[:id])
    end

    def create
        @diary = Diary.new(diary_params)

        if @diary.save
          redirect_to @diary
        else
          render 'new'
        end
    end

    def update
        @diary = Diary.find(params[:id])
       
        if @diary.update(diary_params)
          redirect_to @diary
        else
          render 'edit'
        end
    end

    
    def destroy
        @diary = Diary.find(params[:id])
        @diary.destroy
   
        redirect_to diaries_path
    end

    private
    def diary_params
        params.require(:diary).permit(:foodname, :image)
    end
end

fooddiary/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      log_in user 
      redirect_to user 
    else
      flash.now[:danger] = 'Invalid email/password combination' 
      render 'new'
    end
  end

  def destroy
    log_out 
    redirect_to root_url
  end
    
end

fooddiary/app/controllers/users_controller.rb
class UsersController < ApplicationController
    def create 
        User.create(email: params[:email], 
            password: params[:password], 
            password_confirmation: params[:password_confirmation]) 
            redirect_to :root 
    end

    
end

fooddiary/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  
  def index
  end
end

fooddiary/app/helpers/application_helper.rb
module ApplicationHelper
end

fooddiary/app/helpers/comments_helper.rb
module CommentsHelper
end

fooddiary/app/helpers/diaries_helper.rb
module DiariesHelper
end

fooddiary/app/helpers/sessions_helper.rb
module SessionsHelper
    # 전달된 사용자로 로그인 
    def log_in(user)
        session[:user_id] = user.id 
    end 
    # 현재 로그인 한 사용자를 반환(로그인 한 경우에만) 
    def current_user 
        @current_user ||= User.find_by(id: session[:user_id]) 
    end 
    # 로그인 되어있다면 true 를 그렇지 않다면 false 를 반환 
    def user_signed_in?
        !current_user.nil? 
    end


end

fooddiary/app/helpers/users_helper.rb
module UsersHelper
end

fooddiary/app/helpers/welcome_helper.rb
module WelcomeHelper
end

fooddiary/app/views/comments/_comment.html.erb
<p>
  <strong>calorie:</strong>
  <%= comment.calorie %>
</p>
 
<p>
  <strong>time:</strong>
  <%= comment.time %>
</p>
 
 <p>
  <strong>day:</strong>
  <%= comment.day %>
</p>

<p>
  <strong>bld:</strong>
  <%= comment.bld %>
</p>

<p>
  <%= link_to 'Destroy Comment', [comment.diary, comment],
               method: :delete,
               data: { confirm: 'Are you sure?' } %>
</p>

fooddiary/app/views/comments/_form.html.erb
<%= form_with(model: [ @diary, @diary.comments.build ], local: true) do |form| %>
  <p>
    <%= form.label :calorie %><br>
    <%= form.text_field :calorie %>
  </p>
  <p>
    <%= form.label :time %><br>
    <%= form.text_area :time %>
  </p>

  <p>
    <%= form.label :day %><br>
    <%= form.text_area :day %>
  </p>

  <p>
    <%= form.label :bld %><br>
    <%= form.text_area :bld %>
  </p>
  <p>
    <%= form.submit %>
  </p>
<% end %>

fooddiary/app/views/comments/_from.html.erb
<%= form_with(model: [ @diary, @diary.comments.build ], local: true) do |form| %>
  <p>
    <%= form.label :calorie %><br>
    <%= form.text_field :calorie %>
  </p>
  <p>
    <%= form.label :time %><br>
    <%= form.text_area :time %>
  </p>

  <p>
    <%= form.label :day %><br>
    <%= form.text_area :day %>
  </p>

  <p>
    <%= form.label :bld %><br>
    <%= form.text_area :bld %>
  </p>
  <p>
    <%= form.submit %>
  </p>
<% end %>

fooddiary/app/views/diaries/_bar.html.erb
<div class="navbar">
  <a href="#home">홈페이지</a>
  <a href="#news">뉴스</a>
  <a href="#contact">음식정보d</a>
</div>

<div class="row">
  <div class="column side"></div>
  <div class="column middle">  
<br>
<br>
<br>

fooddiary/app/views/diaries/_footer.html.erb
<footer>
<center>바닥</center>
 
</footer>

fooddiary/app/views/diaries/_form.html.erb
<%= image_tag 'd.jpg' %>

fooddiary/app/views/diaries/edit.html.erb
 
<%= form_with(model: @diary, local: true, multipart: true) do |form| %>
 
  <% if @diary.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@diary.errors.count, "error") %> 에러
      </h2>
      <ul>
        <% @diary.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

<%= render 'bar' %>

<div class="bg-text"><%= render 'form' %></div>

<div class="tb">  
<h1>다이어리 수정</h1>
  <p>
    <%= form.label :음식이름 %><br>
    <%= form.text_field :foodname %>
  </p>
 
  <p>
    <%= form.label :음식사진 %><br>
    <%= form.file_field :image %><br>
  </p>
 
  <p>
    <%= form.submit %>
  </p>
 
<% end %>
 
<%= link_to 'Back', diaries_path %>
</div>


<%= render 'footer' %>

fooddiary/app/views/diaries/index.html.erb
<%= render 'bar' %>



<h1 style="text-align:center">fooddiary</h1>
<div class="bg-text"><%= render 'form' %></div>
<table>
<%= link_to '새일기', new_diary_path %>
  <tr>
    <th colspan="2"></th>
  </tr>
 
  <% @diaries.each do |diary| %>
    <tr>
      <td><%= diary.foodname %></td> 
      <td><img class="img" src="<%= diary.image.url %>"></td>
      <td><%= link_to 'Show', diary_path(diary) %></td>
      <td><%= link_to 'Edit', edit_diary_path(diary) %></td>
      <td><%= link_to 'Destroy', diary_path(diary),
              method: :delete,
              data: { confirm: '삭제?' } %></td>
    </tr>
   </div>
    <% end %>
    <div class="column side"></div>
</table>



<%= render 'footer' %>

fooddiary/app/views/diaries/new.html.erb
<%= form_with scope: :diary, url: diaries_path, local: true, multipart: true do |form| %>
  
  <% if @diary.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@diary.errors.count, "error") %> 오류
      </h2>
      <ul>
        <% @diary.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

<%= render 'bar' %>




<div class="bg-text"><%= render 'form' %></div>


<div class="tb">  
  <p>
    <%= form.label :음식이름 %><br>
    <%= form.text_field :foodname %>
  </p>
 
  <p>
    <%= form.label :음식사진 %><br>
    <%= form.file_field :image %><br>
  </p>
 
  <p>
    <%= form.submit %>
  </p>

 

<% end %>




<%= link_to 'Back', diaries_path %>
</div>

<%= render 'footer' %>

fooddiary/app/views/diaries/show.html.erb
<%= render 'bar' %>

<div class="bg-text"><%= render 'form' %></div>


<div class="tb">
<p>
  <strong><%= @diary.foodname %></strong>
</p>
 
<p>

  <%= @diary.image %>
</p>


<% @diary.comments.each do |comment| %>
 <p>
  <strong>calorie:</strong>
  <%= comment.calorie %>
</p>

<p>
  <strong>날짜:</strong>
  <%= comment.day %>
</p>

<p>
  <strong>먹은시간:</strong>
  <%= comment.time %>
</p>
 
<p>
  <strong>아침,점심,저녁:</strong>
  <%= comment.bld %>
</p>
<% end %>
 

<%= form_with(model: [ @diary, @diary.comments.build ], local: true) do |form| %>
  <p>
    <%= form.label :calorie %><br>
    <%= form.text_field :calorie %>
  </p>
  <p>
    <%= form.label :time %><br>
    <%= form.text_area :time %>
  </p>

  <p>
    <%= form.label :day %><br>
    <%= form.text_area :day %>
  </p>

  <p>
    <%= form.label :bld %><br>
    <%= form.text_area :bld %>
  </p>
  <p>
    <%= form.submit %>
  </p>
<% end %>

<iframe height="500px" src="https://gc201535615.mybluemix.net/">
  <p>이미지 인식</p>
</iframe>
<br>
<%= link_to 'Edit', edit_diary_path(@diary) %> |
<%= link_to 'Back', diaries_path %>
</div>

<br>
<br>
<br>
<br>
<br>
<br>
<%= render 'footer' %>

fooddiary/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Fooddiary</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

fooddiary/app/views/users/new.html.erb
<%= form_tag '/users' do %> 
이메일 
<input type="email" name="email"><br> 
패스워드 
<input type="password" name="password"><br> 
패스워드 확인 
<input type="password" name="password_confirmation"><br> 
<input type="submit" value="회원가입"> 
<% end %>

fooddiary/app/views/welcome/index.html.erb
<!DOCTYPE html>
<html>
<title>f-diary</title>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">

<style>
body {font-family: "Times New Roman", Georgia, Serif;}
h1,h2,h3,h4,h5,h6 {
    font-family: "Playfair Display";
    letter-spacing: 5px;
}
</style>
<body>  

<!-- Navbar (sit on top) -->
<div class="w3-top">
  <div class="w3-bar w3-white w3-padding w3-card" style="letter-spacing:4px;">
    <a href="#home" class="w3-bar-item w3-button">Food diary</a>
    <!-- Right-sided navbar links. Hide them on small screens -->
    <div class="w3-right w3-hide-small">
      <a href="#about" class="w3-bar-item w3-button">소개</a>
      <a href="#menu" class="w3-bar-item w3-button">기능</a>
      <a href="#contact" class="w3-bar-item w3-button">문의</a>
    </div>
  </div>
</div>

<!-- Header -->
<header class="w3-display-container w3-content w3-wide" style="max-width:1600px;min-width:500px" id="home">
 <%= image_tag 'b.jpg' ,alt:'넓1600 높800' %>
  <div class="w3-display-bottomleft w3-padding-large w3-opacity">
    <h1 class="w3-xxlarge"><%= link_to '다이어리 작성', controller: 'diaries' %></h1>
  </div>
</header>

<!-- Page content -->
<div class="w3-content" style="max-width:1100px">

  <!-- About Section -->
  <div class="w3-row w3-padding-64" id="about">
    <div class="w3-col m6 w3-padding-large w3-hide-small">
    <%= image_tag 'a.jpg' ,alt:'넓600 높750' %>
    </div>

    <div class="w3-col m6 w3-padding-large">
      <h1 class="w3-center">소개</h1><br>
      <h5 class="w3-center">칼로리 사진기</h5>
      <p class="w3-large">살을빼려면 칼로리 조절을 해야한다고 합니다 <span class="w3-tag w3-light-grey">칼로리사진기</span>ㅇㅇ.</p>
      <p class="w3-large w3-text-grey w3-hide-medium">Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum consectetur adipiscing elit, sed do eiusmod temporincididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</p>
    </div>
  </div>
  
  <hr>
  
  <!-- Menu Section -->
  <div class="w3-row w3-padding-64" id="menu">
    <div class="w3-col l6 w3-padding-large">
      <h1 class="w3-center">기능들</h1><br>
      <h4>Bread Basket</h4>
      <p class="w3-text-grey">Assortment of fresh baked fruit breads and muffins 5.50</p><br>
    
      <h4>Honey Almond Granola with Fruits</h4>
      <p class="w3-text-grey">Natural cereal of honey toasted oats, raisins, almonds and dates 7.00</p><br>
    
      <h4>Belgian Waffle</h4>
      <p class="w3-text-grey">Vanilla flavored batter with malted flour 7.50</p><br>
    
      <h4>Scrambled eggs</h4>
      <p class="w3-text-grey">Scrambled eggs, roasted red pepper and garlic, with green onions 7.50</p><br>
    
      <h4>Blueberry Pancakes</h4>
      <p class="w3-text-grey">With syrup, butter and lots of berries 8.50</p>    
    </div>
    
    <div class="w3-col l6 w3-padding-large">
    <%= image_tag 'c.jpg' ,alt:'넓100%' %>

    </div>
  </div>

  <hr>

  <!-- Contact Section -->
  <div class="w3-container w3-padding-64" id="contact">
    <h1>문의</h1><br>
    <p>불편하거나 추가할 내용 있으면 알려주세요</p>
    <p class="w3-text-blue-grey w3-large"><b>ㅁㄴㅇㄻㄴㅇㄹ</b></p>
    <p>ㅁㄴㅇㄻㄴㅇㄻㄴㅇㄻㄴㅇ</p>
    <form action="/action_page.php" target="_blank">
      <p><input class="w3-input w3-padding-16" type="text" placeholder="이름" required name="Name"></p>
      <p><input class="w3-input w3-padding-16" type="text" placeholder="메일주소" required name="email"></p>
      <p><input class="w3-input w3-padding-16" type="datetime-local" placeholder="Date and time" required name="date" value="2017-11-16T20:00"></p>
      <p><input class="w3-input w3-padding-16" type="text" placeholder="하고 싶은말" required name="Message"></p>
      <p><button class="w3-button w3-light-grey w3-section" type="submit">SEND MESSAGE</button></p>
    </form>
  </div>
  
<!-- End page content -->
</div>

<!-- Footer -->
<footer class="w3-center w3-light-grey w3-padding-32">
  <p>만든이 <a href="https://github.com/orgs/Ichiban123/dashboard" title="W3.CSS" target="_blank" class="w3-hover-text-green">이치방</a></p>
</footer>

</body>
</html>